// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.GoogleHomePage;
import org.example.Result;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeDriverService;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.net.URL;
import java.util.concurrent.TimeUnit;

import static java.lang.System.out;

public class StackTest {

    protected static ChromeDriver driver;
    protected static GoogleHomePage home;
    protected static Result result;
    protected static String site;



    @BeforeClass
    public void setUp(){
        System.setProperty("webdriver.chrome.driver","resources/chromedriver.exe");
        driver = new ChromeDriver();
        driver.manage().window().maximize();



    }


    @AfterClass
    public void tearDown(){
        driver.quit();
    }
 }
